# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "3db92ab0929e2a86ff8ac5a77e04103db65657a2a524e3e26837753a259e0f5f"
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0cdbfb248a465ffcfd673ef8df1acbf81e138dad0b30ffddc25979c57f421e47"
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eefebdc847c8f28b7145cda8648a28d01e8f0732ed130b73809e477472299156"
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "532e578d1bd3499a8393e1d8be23b784286b091cd9fc00ac3697d204cc3d95f4"
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_linux_arm64.tar.gz"
    end
  end

  name "drift"
  desc "Real-time polyglot codebase health dashboard"
  homepage "https://github.com/greatnessinabox/drift"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drift"

  # No zap stanza required

end
