# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  name "drift"
  desc "Real-time polyglot codebase health dashboard"
  homepage "https://github.com/greatnessinabox/drift"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drift"

  on_macos do
    on_intel do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_darwin_amd64.tar.gz"
      sha256 "b386b1483c14fd464d6403f4b527a696be05a1eff00c3c818cb53ad64fc23091"
    end
    on_arm do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_darwin_arm64.tar.gz"
      sha256 "b81b450186404c584a3e9513ddcf9ba01b43f74b8c58d921607036cd59184e3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_linux_amd64.tar.gz"
      sha256 "90c73900c192150404cd4d874f2760d4747b6855e22793de216258289661cc54"
    end
    on_arm do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_linux_arm64.tar.gz"
      sha256 "5a37b237e8ab109c9530133df30f41044ddec88a495162bb57bea6126d2ebb25"
    end
  end

  # No zap stanza required
end
