# This file was generated by GoReleaser. DO NOT EDIT.
cask "drift" do
  name "drift"
  desc "Real-time polyglot codebase health dashboard"
  homepage "https://github.com/greatnessinabox/drift"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drift"

  on_macos do
    on_intel do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_darwin_amd64.tar.gz"
      sha256 "46a3993da69e9292016720cea5282e1107ace7fcab30386e27ba35f40a189afe"
    end
    on_arm do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_darwin_arm64.tar.gz"
      sha256 "46ac92fa82eaf6117d741da92b811732889fdf138c3a90fe539e9852c2e9c68d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_linux_amd64.tar.gz"
      sha256 "ab54b9de944be9d2753ec261f2fc6f0d5500430933f6015b8583f473a28c8f47"
    end
    on_arm do
      url "https://github.com/greatnessinabox/drift/releases/download/v#{version}/drift_linux_arm64.tar.gz"
      sha256 "928075be6a92f3ad4cff17bf6d8c94d4c613377692d504f7c6adb32ed75e58ed"
    end
  end

  # No zap stanza required
end
